### ISSUE TITLE
Adding (some) journal websites

### ISSUE THREAD

**Issue by larsvilhuber** [ledwindra/replication-code-economics#2]
Parse CrossRef and DataCite (both have an API, there are python packages) for DOIs with "replication" in title.

**Comment by ledwindra** [comment]
Thank you, these are interesting stuffs! Will take a closer look and experiment with them :)

**Comment by ledwindra** [comment]
Hi @larsvilhuber 

So I've added some journals. Steps that I used:
- Get a list of top journals from [IDEAS/RePEc](https://ideas.repec.org/top/top.journals.all.html) (currently top 10)
- For each paper in the corresponding paper, get the DOI and retrieve results from Crossref. For example, see [Econometrica (a list of DOIs in JSON format)](https://github.com/ledwindra/replication-code-economics/tree/main/data/crossref/s-wly-emetrp)
- For each DOI that has linkage to Crossref (some DOIs don't have any), find out whether or not it has any replication code/supplemental material from the journal's website.

So far I've obtained [Econometrica](https://github.com/ledwindra/replication-code-economics/blob/main/data/econometrica.csv) and [Journal of Political Economy](https://github.com/ledwindra/replication-code-economics/blob/main/data/journal-of-political-economy.csv) (links refer to the csv dataset). See code snippet below

```python
>>> import pandas as pd
>>> df = pd.read_csv('data/econometrica.csv')
>>> df[df['has_replication'] == True]
                                     doi  ... has_replication
0    http://dx.doi.org/10.3982/ecta13761  ...            True
2    http://dx.doi.org/10.3982/ecta11530  ...            True
11   http://dx.doi.org/10.3982/ecta15565  ...            True
12   http://dx.doi.org/10.3982/ecta11930  ...            True
15   http://dx.doi.org/10.3982/ecta17489  ...            True
..                                   ...  ...             ...
274  http://dx.doi.org/10.3982/ecta12558  ...            True
276  http://dx.doi.org/10.3982/ecta14176  ...            True
277  http://dx.doi.org/10.3982/ecta14930  ...            True
281  http://dx.doi.org/10.3982/ecta16327  ...            True
284  http://dx.doi.org/10.3982/ecta16262  ...            True

[127 rows x 6 columns]

>>> df[df['doi'] == 'http://dx.doi.org/10.3982/ecta13761'].to_dict()['title']
{0: "['Optimal Development Policies With Financial Frictions']"}
```

Taking http://dx.doi.org/10.3982/ecta13761 as example, in which the URL redirects us to https://www.econometricsociety.org/publications/econometrica/2019/01/01/optimal-development-policies-financial-frictions, we can confirm that it indeed has a replication file

<img width="849" alt="image" src="https://user-images.githubusercontent.com/39021609/114872984-07657400-9e25-11eb-85b4-eaba1fb59391.png">

Does this answer your issue? If yes, this approach should be scaled to other journals (not only top 10). Thank you for the feedback by the way, I learn something new.  😀

**Comment by larsvilhuber** [comment]
Yes, this is excellent!

The problem you may run into at some point (depends on the proxy you are using...) is that for some journals, the link to the replication package is *behind* the paywall. But that can be diagnosed probably by *no* article for a particular journal/year having links to data.


--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

***@***.*** | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ***@***.*** | +1.607-255-2744
________________________________

**Comment by ledwindra** [comment]
Yes, right. I just encountered such problem as well when making a web requests from Oxford Universty Press' journals, such as QJE and Review of Economic Studies. Might have to figure out for this. 

But at least if generally this answers to your issue, I'll proceed with this approach and see whether this could be applied to more journals besides top 10. Thanks again!

**Comment by ledwindra** [comment]
Top 10 econ journals [done](https://github.com/ledwindra/replication-code-economics/releases/tag/v0.1.0)
