### ISSUE TITLE
Augment keywords

### ISSUE THREAD

**Issue by larsvilhuber** [ledwindra/replication-code-economics#3]
AEA deposits mostly use "Data and Code for: " to preface replication packages.

**Comment by ledwindra** [comment]
Thank you for this!

Do you think AEA's deposit from [openICPSR](https://www.openicpsr.org/openicpsr/search/aea/studies;jsessionid=61811CCC3C6E1B567E31E0D11CD1D5A3) can be a good start? Sure many of them have "Data and Code for: " but it looks like we can capture more than that?

**Comment by ledwindra** [comment]
@larsvilhuber 

You may want to check updates from this issue. Here, I've scraped [AEA DOIs](https://www.aeaweb.org/). Then, I've referenced whether the corresponding paper has any deposit on ICPSR. This way, I don't have to hard code **Data and code for:** or something like that. Scraping is currently ongoing (automated via [GitHub Actions](https://github.com/ledwindra/replication-code-economics/actions/workflows/aea.yml) and updated via cron-job). But some examples (JSON data) can be checked [here](https://github.com/ledwindra/replication-code-economics/tree/main/data/aea)

**Comment by larsvilhuber** [comment]
Agreed. But you might want to use this together with an expanded list of keywords as a "truth"/training sample to be able to capture other journal's deposits as well.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

***@***.*** | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ***@***.*** | +1.607-255-2744
________________________________

**Comment by ledwindra** [comment]
Noted, thank you. This will be a starter before moving on to other journals (e.g. econometrica, etc).

**Comment by ledwindra** [comment]
Closing this, additional relevant keywords at least for top 10 econ journals include:
- Supplementary data
- Supplemental data

See [notebook](https://github.com/ledwindra/replication-code-economics/blob/main/replication.ipynb)
