### ISSUE TITLE
Assess quality of linkage

### ISSUE THREAD

**Issue by larsvilhuber** [ledwindra/replication-code-economics#4]
Parse metadata (Datacite, Crossref) or README (Github) for linkage to published articles (DOI or otherwise)

**Comment by ledwindra** [comment]
Thanks! Really cool stuffs that they (Datacite, Crossref) provide the APIs in JSON.

Haven't tried parsing README before but fortunately, from the GitHub's [docs](https://docs.github.com/en/github/searching-for-information-on-github/searching-for-repositories#search-by-repository-name-description-or-contents-of-the-readme-file) it's possible to do that. Cool! Need to figure out at linking DOIs though

**Comment by ledwindra** [comment]
Closing this. Metadata for:
- Crossref for top 10 journals [here](https://github.com/ledwindra/replication-code-economics/tree/main/data/crossref)
- AEA's nine journals on ICPSR [here](https://github.com/ledwindra/replication-code-economics/tree/main/data/aea/aea-metadata)
